---
title: "Homework 6"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE,
                      warning = FALSE, error = TRUE,
                      fig.height = 3)
library(tidyverse)
```


# Preliminaries

- This file should be in `STAT240/homework/hw06` on your local computer.

# Problem 1

For each of the following descriptions, say whether the random variable is reasonably approximated by a binomial random variable or not, and explain your answer. If the variable is binomial, identify $n$ the number of trials and $p$ the probability of success.  If it is not binomial, identify which of the "BINS" assumptions is violated.

(a) A fair die is rolled until a 1 appears, and $X$ denotes the number of rolls.

(b) Twenty of the different Badger basketball players each attempt 1 free throw and $X$ is the total number of successful attempts.

(c) A die is rolled 50 times. Let $X$ be the face that lands up most often.

(d) In a bag of 10 batteries, I know 2 are old. Let $X$ be the number of old batteries I choose when taking a sample of 4 to put into my calculator.

(e) It is reported that 20% of Madison homeowners have installed a home security system. Let $X$ be the number of homes without home security systems installed in a random sample of 100 houses in the Madison city limits.


# Problem 2

(a) Create a data frame with the following columns.
Each row corresponds to a single $\text{Binom}(n, p)$ distribution. The first two columns are the parameters of the distribution.

- `n`, which is always equal to 100
- `p`, which ranges from 0 to 1 by 0.01 $(0, 0.01, 0.02, \ldots , 0.99, 1)$
- `mu`, the mean
- `sigma`, the standard deviation
- `q90`, the 0.9 quantile (or 90th percentile)

(b) Create line plots of the following:
- $\sigma$ versus $p$
- 90th percentile versus $p$

(c) How does the standard deviation change with $p$?

(d) Comment on the relationship between the 90th percentile and $p$.


# Problem 3

The random variable $X$ has the $\text{Binom}(100, 0.2)$ distribution.

(a) Find an integer $a$ so that $P(X \le a) \ge 0.5$. (There are many choices for $a$).  Show the value of $P(X \le a)$ with `pbinom()`.

(b) Find an integer $b$ so that $P(X \ge b) \ge 0.5$. (There are many choices for $b$). Show the value of $P(X \ge b)$ with `pbinom()`. 

(c) Find an integer $c$ so that $P(X \le c) \ge 0.5$ *and* $P(X \ge c) \ge 0.5$. Show the values of $c$, $P(X \le c)$, and $P(X \ge c)$.


# Problem 4

A student decided to guess randomly on their True/False quiz.  The number of questions they answer correctly is $\text{Binom}(10, 0.5)$.  Write code with `dbinom`, `pbinom`, or `qbinom` to calculate each value or probability.

- "I know I must have gotten at least one question right!"

- "I probably got 3 - 5 of the questions right."

- "I feel lucky.  The answers I picked are better than 90% of my other attempts!"

Explain why the 90th percentile is not 9. 


# Problem 5

Match the four binomial distributions given below to the appropriate graph in `p5_choices.png`. Briefly justify your choices.

- Binom(12, 0.5)

- Binom(12, 0.6)

- Binom(10, 0.1)

- Binom(10, 0.3)


# Problem 6

(a) Identify whether each of the statements below are *always true*, *sometimes true*, or *never true* for Binomial random variables.  Briefly explain your answers. You can optionally use R to help make your argument.

- The distribution has no limits and covers the entire number line.

- The 50th percentile is less than the 60th percentile.

- If $\mu$ is the mean of the distribution, then the probability distribution graphically reaches its maximum at $\mu$.

- If $\mu$ is the mean of the distribution, then the probability of getting exactly $\mu$ on a random draw is non-zero.

(b) Repeat part (a), but assess the truth of each statement for Normal random variables.

- The distribution has no limits and covers the entire number line.

- The 50th percentile is less than the 60th percentile.

- If $\mu$ is the mean of the distribution, then the probability distribution graphically reaches its maximum at $\mu$.

- If $\mu$ is the mean of the distribution, then the probability of getting exactly $\mu$ on a random draw is non-zero.


# Problem 7

Use `pnorm` to find the following probabilities on X ~ N(0, 1).

(a) $P(X < -1)$

(b) $P(X > 1)$

(c) $P(0.5 < X < 2)$

(d) $P(|X| > 0.75)$


# Problem 8

Let $X_1$ and $X_2$ be two draws from $X ~ N(10, 4)$. Order the five events below based on which events are least to most likely to occur.

- Event A: $X_1 > 15$
- Event B: $X_1 = 15$
- Event C: $X_1 < 15$
- Event D: $X_1 > 15$ AND $X_2 > 15$
- Event E: $X_1 > X_2$


